version: '3'

services:
  app:
    environment:
      - GOOGLE_ANALYTICS_KEY=${GOOGLE_ANALYTICS_KEY}
    restart: always
    container_name: app
    build:
      context: .
    volumes:
      - ./{{ app_name }}:/app/{{ app_name }}
    ports:
      - "8000:8000"
  devtools:
    restart: always
    container_name: devtools
    image: node:8.16.0-jessie
    volumes:
      - ./package.json:/devtools/prereq-map/package.json
      - ./webpack.config.js:/devtools/prereq-map/webpack.config.js
      - ./{{ app_name }}:/devtools/prereq-map/{{ app_name }}
    working_dir: /devtools/prereq-map
    command: bash -c "yes yes | npm install; npx webpack --watch --mode=development"
