version: '3.4'

services:
  app:
    build:
      context: .
      target: app-container
    restart: always
    container_name: app_name_app
    environment:
      - GOOGLE_ANALYTICS_KEY=${GOOGLE_ANALYTICS_KEY}
    volumes:
      - ./app_name:/app/app_name
      - statics-volume:/static
    ports:
      - "${RUNSERVER_PORT:-8000}:8000"
    stdin_open: true
    tty: true
  devtools:
    build:
      context: .
      target: wpack
    restart: always
    container_name: app_name_devtools
    volumes:
      - ./app_name:/app/app_name
      - statics-volume:/static
    command: npx webpack --watch --mode=development
    stdin_open: true
    tty: true
volumes:
  statics-volume:
